name: Trivy IaC Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_iac_scan:
    name: Trivy IaC Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.20.0
      
      - name: Scan Infrastructure as Code with Trivy
        run: |
          trivy iac --exit-code 1 --severity HIGH,CRITICAL /reference-architecture/azure/cloud-init/
